version: '3.9'

services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - nlp
    networks:
      - general-network
    restart: always

  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - general-network

  backend:
    build: ./backend
    expose:
      - "8080"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    networks:
      - general-network
  
  db:
    image: mysql:8.0
    command: 
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--init-connect='SET NAMES utf8mb4'"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - general-network
    restart: always
  
  nlp:
    build: ./nlp
    expose:
      - "8000" 
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:${DB_PASS}@db:3306/${DB_NAME}?charset=utf8mb4
    env_file:
      - ./nlp/.env.example
    networks:
      - general-network
    restart: always

networks:
  general-network:
    driver: bridge

volumes:
  mysql_data:
