version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - general-network

  backend:
    build: ./backend
    ports: 
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - general-network
    restart: always
  
  db:
    image: mysql:8.0
    command: 
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--init-connect='SET NAMES utf8mb4'"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - general-network
    restart: always
  
  # nlp:
  #   build: ./nlp
  #   expose:
  #     - "8000" 
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=mysql+pymysql://root:${DB_PASS}@db:3306/${DB_NAME}?charset=utf8mb4
  #   env_file:
  #     - ./nlp/.env.example
  #   networks:
  #     - general-network
  #   restart: always

networks:
  general-network:
    driver: bridge

volumes:
  mysql_data:
