version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - general-network

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - general-network
    restart: always
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - general-network
    restart: always

  # Email Worker
 email_worker:
   build: ./nlp
   env_file: ./nlp/.env
   depends_on:
     - db
   networks:
     - general-network
   command: python app/email_worker.py
   restart: unless-stopped

  # NLP API
 nlp_api:
   build: ./nlp
   env_file: ./nlp/.env
   depends_on:
     - db
   networks:
     - general-network
   restart: unless-stopped

  # Telegram Bot
 tg_bot:
   build: ./tg_bot
   env_file: ./tg_bot/.env
   depends_on:
     - nlp_api
   networks:
     - general-network
   restart: unless-stopped

networks:
  general-network:
    driver: bridge

volumes:
  mysql_data:
